GET http://localhost:3000/api/user

###
GET http://localhost:3000/api/user/?62b4883352dcf7ba56465bd3
Content-Type: application/json
###

POST  http://localhost:3000/api/user
Content-Type: application/json

{
    "firstname" : "Francis",
    "lastname" : "World",
    "email" : "codingfrancis100@gmail.com",
    "password" : "!@Password123345",
    "username" : "hello-world",
    "contact" : 189329,
    "complaints" : [1,5,7]
}

###

 
DELETE http://localhost:3000/api/user/?62b0f9ddf23be00fdff37c29


### 


PUT http://localhost:3000/api/user/?62b0fa38f23be00fdff37c2c
Content-Type: application/json

{
    "firstname": "Joseph"
}